// Generated by scripts/build_extensions.py from native Kitsuvo rules.
globalThis.KitsuvoRules = {
  "hosts": [
    [
      ".lovable.app",
      "Lovable",
      55
    ],
    [
      ".lovableproject.com",
      "Lovable",
      55
    ],
    [
      ".gptengineer.app",
      "Lovable",
      55
    ],
    [
      ".lovable.run",
      "Lovable",
      55
    ],
    [
      ".lovable.sh",
      "Lovable",
      55
    ],
    [
      ".bolt.host",
      "Bolt",
      50
    ],
    [
      ".bolt.new",
      "Bolt",
      50
    ],
    [
      ".vusercontent.net",
      "v0",
      50
    ],
    [
      ".v0.app",
      "v0",
      50
    ],
    [
      ".v0.build",
      "v0",
      50
    ],
    [
      ".base44.app",
      "Base44",
      50
    ],
    [
      ".base44-sandbox.com",
      "Base44",
      50
    ],
    [
      ".mocha.app",
      "Mocha",
      45
    ],
    [
      ".mochausercontent.com",
      "Mocha",
      45
    ],
    [
      ".mocha-sandbox.dev",
      "Mocha",
      45
    ],
    [
      ".builtwithrocket.new",
      "Rocket",
      45
    ],
    [
      ".rocketpreview.app",
      "Rocket",
      45
    ],
    [
      ".lp.dev",
      "Leap",
      45
    ],
    [
      ".macaly.app",
      "Macaly",
      45
    ],
    [
      ".macaly-app.com",
      "Macaly",
      45
    ],
    [
      ".magicpatterns.app",
      "Magic Patterns",
      45
    ],
    [
      ".magicpatternsapp.com",
      "Magic Patterns",
      45
    ],
    [
      ".gamma.site",
      "Gamma",
      40
    ],
    [
      ".manus.space",
      "Manus",
      50
    ],
    [
      ".created.app",
      "Create (Anything)",
      45
    ],
    [
      ".emergentagent.com",
      "Emergent",
      50
    ],
    [
      ".emergent.host",
      "Emergent",
      50
    ],
    [
      ".emergent.cloud",
      "Emergent",
      50
    ],
    [
      ".figma.site",
      "Figma Make",
      35
    ],
    [
      ".durable.co",
      "Durable",
      45
    ],
    [
      ".replit.app",
      "Replit",
      25
    ],
    [
      ".replit.dev",
      "Replit",
      25
    ],
    [
      ".repl.co",
      "Replit",
      20
    ]
  ],
  "markup": [
    [
      "data-lov-id",
      "Lovable",
      "Lovable component tagger attributes (data-lov-id)",
      60
    ],
    [
      "lovable-tagger",
      "Lovable",
      "lovable-tagger build plugin",
      55
    ],
    [
      "cdn.gpteng.co",
      "Lovable",
      "GPT Engineer / Lovable script (cdn.gpteng.co)",
      55
    ],
    [
      "gptengineer.js",
      "Lovable",
      "GPT Engineer / Lovable script (gptengineer.js)",
      55
    ],
    [
      "lovable generated project",
      "Lovable",
      "Lovable default meta description",
      55
    ],
    [
      "lovable.dev/opengraph-image",
      "Lovable",
      "Lovable default social image",
      45
    ],
    [
      "edit with lovable",
      "Lovable",
      "\"Edit with Lovable\" badge",
      50
    ],
    [
      "made with bolt",
      "Bolt",
      "\"Made with Bolt\" badge",
      50
    ],
    [
      "built with bolt",
      "Bolt",
      "\"Built with Bolt\" badge",
      50
    ],
    [
      "bolt.new/?rid",
      "Bolt",
      "Bolt referral badge link",
      45
    ],
    [
      "built with v0",
      "v0",
      "\"Built with v0\" badge",
      50
    ],
    [
      "made with emergent",
      "Emergent",
      "\"Made with Emergent\" badge",
      50
    ],
    [
      "emergent-badge",
      "Emergent",
      "Emergent badge element",
      50
    ],
    [
      "app.base44.com",
      "Base44",
      "Base44 runtime calls (app.base44.com)",
      45
    ],
    [
      "made with manus",
      "Manus",
      "\"Made with Manus\" badge",
      50
    ],
    [
      "replit-dev-banner",
      "Replit",
      "Replit dev banner script",
      35
    ],
    [
      "replit-badge",
      "Replit",
      "Replit badge",
      30
    ],
    [
      "/lovable-uploads/",
      "Lovable",
      "Images uploaded through Lovable (/lovable-uploads/)",
      50
    ],
    [
      "/~flock.js",
      "Lovable",
      "Lovable runtime script (/~flock.js)",
      50
    ],
    [
      "js:lov_selector_script_version",
      "Lovable",
      "Lovable selector script global (LOV_SELECTOR_SCRIPT_VERSION)",
      50
    ],
    [
      "bolt.new/badge.js",
      "Bolt",
      "Bolt badge script (bolt.new/badge.js)",
      50
    ],
    [
      "made in bolt",
      "Bolt",
      "\"Made in Bolt\" badge",
      45
    ],
    [
      "same-assets.com",
      "Same",
      "Assets served by Same (same-assets.com)",
      45
    ],
    [
      "assets.emergent.sh",
      "Emergent",
      "Emergent asset host (assets.emergent.sh)",
      45
    ],
    [
      "cdn.durable.co",
      "Durable",
      "Durable asset host (cdn.durable.co)",
      40
    ],
    [
      "cdn.b12.io",
      "B12",
      "B12 asset host (cdn.b12.io)",
      30
    ],
    [
      "data-dyad-id",
      "Dyad",
      "Dyad component tagger attributes (data-dyad-id)",
      55
    ],
    [
      "data-dyad-name",
      "Dyad",
      "Dyad component tagger attributes (data-dyad-name)",
      50
    ],
    [
      "made with dyad",
      "Dyad",
      "\"Made with Dyad\" badge",
      50
    ],
    [
      "made with ai in macaly",
      "Macaly",
      "\"Made with AI in Macaly\" badge",
      50
    ],
    [
      "cdn.macaly.app",
      "Macaly",
      "Macaly asset host (cdn.macaly.app)",
      45
    ],
    [
      "assets.gammahosted.com",
      "Gamma",
      "Gamma site assets (assets.gammahosted.com)",
      45
    ],
    [
      "gamma-badge",
      "Gamma",
      "Gamma badge",
      40
    ],
    [
      "js:gammasiteanimationsinitialized",
      "Gamma",
      "Gamma site runtime global",
      45
    ],
    [
      "aistudiocdn.com",
      "Google AI Studio",
      "Google AI Studio import map (aistudiocdn.com)",
      45
    ]
  ],
  "generators": [
    [
      "lovable",
      "Lovable",
      55
    ],
    [
      "gpt engineer",
      "Lovable",
      55
    ],
    [
      "v0",
      "v0",
      50
    ],
    [
      "bolt",
      "Bolt",
      50
    ],
    [
      "durable",
      "Durable",
      45
    ],
    [
      "10web",
      "10Web AI",
      35
    ],
    [
      "hostinger horizons",
      "Hostinger Horizons",
      45
    ]
  ],
  "meta": [
    [
      "meta[name=author]",
      "lovable",
      "Lovable",
      "Lovable default author tag"
    ],
    [
      "meta[name='twitter:site']",
      "@lovable",
      "Lovable",
      "Lovable default Twitter card"
    ],
    [
      "meta[name=apple-mobile-web-app-title]",
      "base44",
      "Base44",
      "Base44 default app title"
    ]
  ],
  "humanGenerators": [
    "wordpress",
    "drupal",
    "joomla",
    "hugo",
    "jekyll",
    "ghost",
    "mediawiki",
    "docusaurus",
    "eleventy"
  ],
  "sensitiveHosts": [
    "accounts.google.com",
    "accounts.youtube.com",
    "myaccount.google.com",
    "login.microsoftonline.com",
    "login.live.com",
    "login.microsoft.com",
    "account.live.com",
    "appleid.apple.com",
    "idmsa.apple.com",
    "account.apple.com",
    "auth.openai.com",
    "login.yahoo.com"
  ],
  "sensitiveSuffixes": [
    ".okta.com",
    ".oktapreview.com",
    ".auth0.com"
  ]
};
